name: "PR checks"

on:
  pull_request:
    branches:
      - main
      - "release/**"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    uses: ./.github/workflows/typecheck.yml

  units:
    uses: ./.github/workflows/unit-tests.yml
