name: "Unit tests"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.33.2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.20.0
          cache: "pnpm"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm run test --filter "@pkgring/*" || echo "no tests yet"
